# Generated by Django 4.2.6 on 2024-01-19 01:24

import designsafe.apps.api.projects_v2.models.project_metadata
from django.conf import settings
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectMetadata",
            fields=[
                (
                    "uuid",
                    models.CharField(
                        default=designsafe.apps.api.projects_v2.models.project_metadata.uuid_pk,
                        editable=False,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Metadata namespace, e.g. 'designsafe.project'",
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "value",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="JSON document containing file metadata, including title/description",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "association_ids",
                    models.JSONField(
                        default=list,
                        help_text="(DEPRECATE IN V3) Tapis V2 association IDs.",
                    ),
                ),
                (
                    "base_project",
                    models.ForeignKey(
                        help_text="Base project containing this entity.For top-level project metadata, this is `self`.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects_v2_api.projectmetadata",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        help_text="Users who have access to a project.",
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(models.F("value__projectId"), name="value_project_id"),
                    models.Index(fields=["name"], name="projects_v2_name_2b10f5_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="projectmetadata",
            constraint=models.UniqueConstraint(
                models.F("value__projectId"),
                condition=models.Q(("name", "designsafe.project")),
                name="unique_id_per_project",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmetadata",
            constraint=models.UniqueConstraint(
                condition=models.Q(("name", "designsafe.project.graph")),
                fields=("base_project_id",),
                name="unique_graph_per_project",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmetadata",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("name", "designsafe.project"),
                    ("value__projectId__isnull", True),
                    _negated=True,
                ),
                name="base_projectId_not_null",
            ),
        ),
    ]
