# Generated by Django 4.2.6 on 2024-01-09 06:03

import designsafe.apps.api.projects_v2.models.project_metadata
from django.conf import settings
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectMetadata",
            fields=[
                (
                    "uuid",
                    models.CharField(
                        default=designsafe.apps.api.projects_v2.models.project_metadata.uuid_pk,
                        editable=False,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "value",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder
                    ),
                ),
                (
                    "base_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects_v2_api.projectmetadata",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="projects", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(models.F("value__projectId"), name="value_project_id"),
                    models.Index(fields=["name"], name="projects_v2_name_2b10f5_idx"),
                ],
            },
        ),
    ]
