# Generated by Django 4.2.27 on 2026-01-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects_v2_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmetadata",
            name="is_publishing",
            field=models.BooleanField(default=False),
        ),
    ]
