# Generated by Django 4.2.6 on 2024-01-10 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("projects_v2_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmetadata",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
