# Generated by Django 4.2.6 on 2024-01-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects_v2_api", "0002_alter_projectmetadata_created"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="projectmetadata",
            constraint=models.UniqueConstraint(
                models.F("value__projectId"),
                condition=models.Q(("name", "designsafe.project")),
                name="unique_id_per_project",
            ),
        ),
    ]
