# Generated by Django 4.2.6 on 2024-01-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects_v2_api", "0004_projectmetadata_association_ids_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="projectmetadata",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("name", "designsafe.project"),
                    ("value__projectId__isnull", True),
                    _negated=True,
                ),
                name="base_projectId_not_null",
            ),
        ),
    ]
