# Generated by Django 4.2.6 on 2024-01-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects_v2_api", "0005_projectmetadata_base_projectid_not_null"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="projectmetadata",
            constraint=models.UniqueConstraint(
                condition=models.Q(("name", "designsafe.project.graph")),
                fields=("base_project_id",),
                name="unique_graph_per_project",
            ),
        ),
    ]
