# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-09-04 20:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def insert_data(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    DesignSafeProfileNHInterests = apps.get_model("designsafe_accounts", "DesignSafeProfileNHInterests")
    data = [
      "Coastal engineering",
      "Earthquake",
      "Geotechnical",
      "Lifeline infrastructure",
      "Social sciences and/or policy",
      "Tsunami",
      "Wind"
    ]
    for d in data:
        obj = DesignSafeProfileNHInterests(description=d)
        obj.save()


def add_research_activities_data(apps, schema_editor):
    DesignSafeProfileResearchActivities = apps.get_model("designsafe_accounts", "DesignSafeProfileResearchActivities")
    data = [
      "Already performed research in the NHERI program",
      "Performed research in the NEES program",
      "Performed research in the NHERI subject area but not in the NEES or NHERI programs",
      "Planning to perform research in the NHERI program",
      "Involved in education in the NHERI subject areas",
      "No direct involvement in reseach or education in the NHERI subject areas"
    ]
    for d in data:
        obj = DesignSafeProfileResearchActivities(description=d)
        obj.save()


def set_default_notification_prefs(apps, schema_editor):
    # Find users with no prefs set
    User = apps.get_model(settings.AUTH_USER_MODEL)
    NotificationPreferences = apps.get_model(
        "designsafe_accounts", "NotificationPreferences")
    users = User.objects.filter(Q(notification_preferences__isnull=True))
    for user in users:
        prefs = NotificationPreferences(user=user)
        prefs.save()


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# designsafe.apps.accounts.migrations.0008_auto_20161118_2025
# designsafe.apps.accounts.migrations.0011_auto_20161121_1643
# designsafe.apps.accounts.migrations.0015_create_notification_preferences

class Migration(migrations.Migration):

    replaces = [(b'designsafe_accounts', '0001_initial'), (b'designsafe_accounts', '0002_notificationpreferences'), (b'designsafe_accounts', '0003_auto_20160907_1419'), (b'designsafe_accounts', '0004_designsafeprofile_bio'), (b'designsafe_accounts', '0005_designsafeprofile_website'), (b'designsafe_accounts', '0006_auto_20161117_2237'), (b'designsafe_accounts', '0007_auto_20161118_1932'), (b'designsafe_accounts', '0008_auto_20161118_2025'), (b'designsafe_accounts', '0009_auto_20161121_1633'), (b'designsafe_accounts', '0010_designsafeprofile_reseach_activities'), (b'designsafe_accounts', '0011_auto_20161121_1643'), (b'designsafe_accounts', '0012_auto_20161121_1711'), (b'designsafe_accounts', '0013_auto_20161206_1623'), (b'designsafe_accounts', '0014_auto_20170911_1503'), (b'designsafe_accounts', '0015_create_notification_preferences'), (b'designsafe_accounts', '0016_designsafeprofile_agree_to_account_limit')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignSafeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethnicity', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('bio', models.CharField(default=None, max_length=4096, null=True)),
                ('website', models.CharField(default=None, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcements', models.BooleanField(default=True, help_text='Receive occasional announcements from DesignSafe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='notificationpreferences',
            options={'permissions': (('view_notification_subscribers', 'Can view list of users subscribed to a notification type'),)},
        ),
        migrations.AlterField(
            model_name='notificationpreferences',
            name='announcements',
            field=models.BooleanField(default=True, verbose_name='Receive occasional announcements from DesignSafe'),
        ),
        migrations.CreateModel(
            name='DesignSafeProfileNHInterests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='designsafeprofile',
            name='nh_interests',
            field=models.ManyToManyField(to=b'designsafe_accounts.DesignSafeProfileNHInterests'),
        ),
        migrations.RunPython(
            code=insert_data,
        ),
        migrations.CreateModel(
            name='DesignSafeProfileResearchActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='designsafeprofile',
            name='professional_level',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='designsafeprofile',
            name='reseach_activities',
            field=models.ManyToManyField(to=b'designsafe_accounts.DesignSafeProfileResearchActivities'),
        ),
        migrations.RunPython(
            code=add_research_activities_data,
        ),
        migrations.RenameField(
            model_name='designsafeprofile',
            old_name='reseach_activities',
            new_name='research_activities',
        ),
        migrations.AddField(
            model_name='designsafeprofile',
            name='orcid_id',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='designsafeprofile',
            name='bio',
            field=models.CharField(blank=True, default=None, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='designsafeprofile',
            name='website',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='designsafe',
            field=models.BooleanField(default=True, verbose_name='DesignSafe: to communicate new features, planned outages.'),
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='tutorials',
            field=models.BooleanField(default=True, verbose_name='Tutorials: to communicate DesignSafe training opportunities.'),
        ),
        migrations.AlterField(
            model_name='notificationpreferences',
            name='announcements',
            field=models.BooleanField(default=True, verbose_name='Announcements: to communicate EF Workshops, NHERI Newsletter, Student Opportunities, etc.'),
        ),
        migrations.RunPython(
            code=set_default_notification_prefs,
        ),
        migrations.AddField(
            model_name='designsafeprofile',
            name='agree_to_account_limit',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
