# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-15 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("designsafe_accounts", "0015_create_notification_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="designsafeprofile",
            name="agree_to_account_limit",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
