# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-04 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designsafe_accounts', '0018_auto_20191014_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='designsafeprofile',
            name='nh_interests_primary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nh_interests_primary', to='designsafe_accounts.DesignSafeProfileNHInterests'),
        ),
    ]
