# Generated by Django 4.2.6 on 2023-11-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("designsafe_accounts", "0019_designsafeprofile_nh_interests_primary"),
    ]

    operations = [
        migrations.AddField(
            model_name="designsafeprofile",
            name="institution",
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
