# Generated by Django 4.2.11 on 2024-08-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("designsafe_accounts", "0020_designsafeprofile_institution"),
    ]

    operations = [
        migrations.AddField(
            model_name="designsafeprofile",
            name="homedir",
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
