# Generated by Django 4.2.11 on 2024-10-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("designsafe_accounts", "0021_designsafeprofile_homedir"),
    ]

    operations = [
        migrations.AddField(
            model_name="designsafeprofile",
            name="setup_complete",
            field=models.BooleanField(default=False),
        ),
    ]
