# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-15 22:39
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings
from google.oauth2.credentials import Credentials
from oauth2client.contrib.django_util.models import CredentialsField


def create_credential_model(apps, schema_editor):
    # Find users that already have Google Drive access set up,
    # and consolidate tokens into CredentialsField model

    GoogleDriveUserToken = apps.get_model(
        "googledrive_integration", "GoogleDriveUserToken")
    tokens = GoogleDriveUserToken.objects.all()
    for google_token in tokens:
        credentials = {
            'token': google_token.token,
            'refresh_token': google_token.refresh_token,
            'token_uri': google_token.token_uri,
            'client_id': settings.GOOGLE_OAUTH2_CLIENT_ID,
            'client_secret': settings.GOOGLE_OAUTH2_CLIENT_SECRET,
            'scopes': [google_token.scopes]
        }
        
        google_token.credential = Credentials(**credentials)
        google_token.save()

        # google_token.delete()
        # token = GoogleDriveUserToken(
        #     user=google_token.user,
        #     credentials=Credentials(**credentials)
        # )

        # token.save()


class Migration(migrations.Migration):

    dependencies = [
        ('googledrive_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googledriveusertoken',
            name='credential',
            field=CredentialsField(null=True),
        ),
        migrations.RunPython(create_credential_model),
        migrations.RemoveField(
            model_name='googledriveusertoken',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='googledriveusertoken',
            name='scopes',
        ),
        migrations.RemoveField(
            model_name='googledriveusertoken',
            name='token',
        ),
        migrations.RemoveField(
            model_name='googledriveusertoken',
            name='token_uri',
        ),
    ]
