# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-11 21:58
from __future__ import unicode_literals

import designsafe.apps.googledrive_integration.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('googledrive_integration', '0002_auto_20180215_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googledriveusertoken',
            name='credential',
            field=designsafe.apps.googledrive_integration.models.CredentialsField(null=True),
        ),
    ]
