# Generated by Django 4.2.20 on 2025-06-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropbox_integration', '0002_auto_20170202_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropboxusertoken',
            name='access_token',
            field=models.CharField(max_length=2048),
        ),
    ]
