# Generated by Django 4.2.20 on 2025-06-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("dropbox_integration", "0003_alter_dropboxusertoken_access_token"),
        ("dropbox_integration", "0004_dropboxusertoken_refresh_token"),
    ]

    dependencies = [
        ("dropbox_integration", "0002_auto_20170202_1714"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dropboxusertoken",
            name="access_token",
            field=models.CharField(max_length=2048),
        ),
        migrations.AddField(
            model_name="dropboxusertoken",
            name="refresh_token",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
