# Generated by Django 4.2.6 on 2024-04-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications_v2_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
    ]
