# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-23 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("designsafe_licenses", "0003_auto_20180125_2251"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matlablicense",
            name="license_type",
        ),
    ]
