# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-10-19 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_plugins', '0003_auto_20170824_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsiveembedplugin',
            name='allowfullscreen',
            field=models.BooleanField(default=True, verbose_name='Allow Fullscreen'),
        ),
        migrations.AlterField(
            model_name='responsiveembedplugin',
            name='aspect',
            field=models.CharField(choices=[('16by9', '16by9'), ('4by3', '4by3'), ('podcast', 'podcast')], max_length=255),
        ),
    ]
