# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-11-13 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_plugins', '0004_auto_20201019_1920'),
        ('cms_plugins', '0004_auto_20201016_2026'),
    ]

    operations = [
    ]
