# Generated by Django 4.2.6 on 2024-04-15 21:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileMetaModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("system", models.CharField(max_length=255)),
                ("path", models.CharField(max_length=4096)),
                ("value", models.JSONField()),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("system", "path")},
            },
        ),
    ]
