# Generated by Django 4.2.6 on 2024-04-18 16:50
# Custom migration to handle unique constraint of system/path in "value"
from django.db import migrations, models
import django.db.models.expressions as expressions


class Migration(migrations.Migration):
    dependencies = [
        ("filemeta_api", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="filemetamodel",
            constraint=models.UniqueConstraint(
                expressions.F("value__system"),
                expressions.F("value__path"),
                name="unique_system_path",
            ),
        ),
    ]
