# Generated by Django 4.2.15 on 2025-06-23 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filemeta_api', '0002_auto_20240418_1650'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='filemetamodel',
            name='unique_system_path',
        ),
    ]
