# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-09-04 20:50
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import Group
from designsafe.apps.rapid.models import RapidNHEventType, RapidNHEvent


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# designsafe.apps.rapid.migrations.0001_initial
# designsafe.apps.rapid.migrations.0003_auto_20170724_2110


def add_rapid_event_types(apps, schema_editor):
    RapidNHEvent.init()
    RapidNHEventType.init()
    events = [
        {"name": "earthquake", "display_name": "Earthquake"},
        {"name": "landslide", "display_name": "Landslide"},
        {"name": "tsunami", "display_name": "Tsunami"},
        {"name": "flood", "display_name": "Flood"},
        {"name": "hurricane", "display_name": "Hurricane/Typhoon"},
        {"name": "tornado", "display_name": "Tornado"}
    ]

    s = RapidNHEventType.search()

    for ev in events:
        q = s.query("match", name=ev["name"])
        if q.count() > 0:
            continue
        et = RapidNHEventType(**ev)
        et.save()


def add_group(apps, scema_editor):
    group, created = Group.objects.get_or_create(name='Rapid Admin')


class Migration(migrations.Migration):

    replaces = [(b'rapid', '0001_initial'), (b'rapid', '0002_auto_20170627_2004'), (b'rapid', '0003_auto_20170724_2110')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            code=add_rapid_event_types,
        ),
        migrations.RunPython(
            code=add_group,
        ),
    ]
