# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-09-04 20:23
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'designsafe_auth', '0001_initial'), (b'designsafe_auth', '0002_auto_20160209_0427')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgaveOAuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('expires_in', models.BigIntegerField()),
                ('created', models.BigIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agave_oauth', to=settings.AUTH_USER_MODEL)),
                ('scope', models.CharField(default='default', max_length=255)),
                ('token_type', models.CharField(default='bearer', max_length=255)),
            ],
        ),
    ]
