# Generated by Django 2.2.5 on 2019-09-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designsafe_auth', '0001_squashed_0002_auto_20160209_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agaveoauthtoken',
            name='scope',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='agaveoauthtoken',
            name='token_type',
            field=models.CharField(max_length=255),
        ),
    ]
