# Generated by Django 4.2.6 on 2024-02-28 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("designsafe_auth", "0002_auto_20160209_0427"),
    ]

    operations = [
        migrations.CreateModel(
            name="TapisOAuthToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.CharField(max_length=2048)),
                ("refresh_token", models.CharField(max_length=2048)),
                ("expires_in", models.BigIntegerField()),
                ("created", models.BigIntegerField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tapis_oauth",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="AgaveOAuthToken",
        ),
    ]
