# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-09-04 20:10
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'box_integration', '0001_initial'), (b'box_integration', '0002_boxusertoken_box_user_id'), (b'box_integration', '0003_auto_20160328_2215')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxUserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='box_user_token', to=settings.AUTH_USER_MODEL)),
                ('box_user_id', models.CharField(default='0', max_length=48)),
            ],
        ),
    ]
