# Generated by Django 2.2.5 on 2019-09-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_integration', '0001_squashed_0003_auto_20160328_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxusertoken',
            name='box_user_id',
            field=models.CharField(max_length=48),
        ),
    ]
