# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-08-04 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20160301_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Text for the alert message')),
                ('display', models.BooleanField()),
            ],
        ),
    ]
