# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-24 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_auto_20170718_1602"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Broadcast",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
