# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-04-17 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0005_auto_20170824_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageAlert',
            fields=[
                ('name', models.CharField(max_length=120, primary_key=True, serialize=False, unique=True)),
                ('alert_type', models.CharField(choices=[('alert-warning', 'WARNING'), ('alert-danger', 'DANGER'), ('alert-info', 'INFO'), ('alert-success', 'SUCCESS')], default='alert-warning', max_length=20)),
                ('message', models.TextField(help_text='Page alert message text.')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
