# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-09 19:26


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='action_link',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_link',
            field=models.TextField(default=b''),
        ),
    ]
