# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-17 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_api', '0002_auto_20180309_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='jobid',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='notification',
            name='jobid',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
