# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-10-19 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications_api", "0003_auto_20180417_2012"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcast",
            name="action_link",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="broadcast",
            name="extra",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="broadcast",
            name="message",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="broadcast",
            name="operation",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="notification",
            name="action_link",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="notification",
            name="extra",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="notification",
            name="operation",
            field=models.CharField(default="", max_length=255),
        ),
    ]
