# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-08 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppDescription",
            fields=[
                (
                    "appid",
                    models.CharField(
                        max_length=120, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "appdescription",
                    models.TextField(
                        help_text=b"App dropdown description text for apps that have a dropdown."
                    ),
                ),
            ],
        ),
    ]
