# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-08 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appId', models.CharField(max_length=120, unique=True)),
                ('appDescription', models.TextField(help_text=b'App dropdown description text for apps that have a dropdown.')),
            ],
        ),
    ]
