# Generated by Django 2.2.5 on 2019-09-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdescription',
            name='appDescription',
            field=models.TextField(help_text='App dropdown description text for apps that have a dropdown.'),
        ),
    ]
