# Generated by Django 4.2.6 on 2024-01-25 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [
        ("workspace", "0003_apptraycategory_appitem_appbundle"),
        ("workspace", "0004_apptrayentry_remove_appitem_category_and_more"),
    ]

    dependencies = [
        ("workspace", "0002_auto_20200423_1940"),
        ("cms", "0022_auto_20180620_1551"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppTrayCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="A category for the app tray",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Category priority, where higher number tabs appear before lower ones",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AppItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="The display name of this app in the Apps Tray.",
                        max_length=64,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rwhale", "rWHALE"),
                            ("hazmapper", "Hazmapper"),
                            ("compress", "Compress"),
                            ("opensees-stko", "OpenSees-STKO"),
                            ("stko", "STKO"),
                            ("openfoam", "OpenFOAM"),
                            ("blender", "Blender"),
                            ("matlab", "MATLAB"),
                            ("ngl", "NGL"),
                            ("paraview", "Paraview"),
                            ("visit", "VisIt"),
                            ("jupyter", "Jupyter"),
                            ("qgis", "QGIS"),
                            ("adcirc", "ADCIRC"),
                            ("opensees", "OpenSees"),
                            ("ls-dyna", "LS-DYNA"),
                            ("ls-pre/post", "LS-Pre/Post"),
                            ("dakota", "Dakota"),
                            ("clawpack", "Clawpack"),
                            ("ansys", "Ansys"),
                            ("swbatch", "swbatch"),
                            ("extract", "Extract"),
                        ],
                        help_text="The icon associated with this app.",
                        max_length=64,
                    ),
                ),
                (
                    "popular",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as popular on tools & apps overview.",
                    ),
                ),
                (
                    "license_type",
                    models.CharField(
                        choices=[("OS", "Open Source"), ("LS", "Licensed")],
                        default="OS",
                        help_text="License Type",
                        max_length=2,
                    ),
                ),
                (
                    "available",
                    models.BooleanField(
                        default=True, help_text="App visibility in app tray"
                    ),
                ),
                (
                    "app_id",
                    models.CharField(
                        help_text="The id of this app or app bundle. The id appears in the unique url path to the app.",
                        max_length=64,
                    ),
                ),
                (
                    "app_type",
                    models.CharField(
                        choices=[("tapis", "Tapis"), ("html", "HTML")],
                        default="tapis",
                        help_text="Application type",
                        max_length=10,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="The version number of the app. The app id + version denotes a unique app",
                        max_length=64,
                    ),
                ),
                (
                    "html",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="HTML definition to display when Application is loaded",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="The category for this app entry.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workspace.apptraycategory",
                    ),
                ),
                (
                    "overview",
                    models.CharField(
                        blank=True,
                        help_text="Link to overview page for this app.",
                        max_length=128,
                    ),
                ),
                (
                    "related_apps",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Related apps that will display on app overview page",
                        to="workspace.appitem",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RenameField(
            model_name="appdescription",
            old_name="appDescription",
            new_name="appdescription",
        ),
        migrations.RenameField(
            model_name="appdescription",
            old_name="appId",
            new_name="appid",
        ),
        migrations.CreateModel(
            name="AppBundle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="The display name of this app in the Apps Tray.",
                        max_length=64,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rwhale", "rWHALE"),
                            ("hazmapper", "Hazmapper"),
                            ("compress", "Compress"),
                            ("opensees-stko", "OpenSees-STKO"),
                            ("stko", "STKO"),
                            ("openfoam", "OpenFOAM"),
                            ("blender", "Blender"),
                            ("matlab", "MATLAB"),
                            ("ngl", "NGL"),
                            ("paraview", "Paraview"),
                            ("visit", "VisIt"),
                            ("jupyter", "Jupyter"),
                            ("qgis", "QGIS"),
                            ("adcirc", "ADCIRC"),
                            ("opensees", "OpenSees"),
                            ("ls-dyna", "LS-DYNA"),
                            ("ls-pre/post", "LS-Pre/Post"),
                            ("dakota", "Dakota"),
                            ("clawpack", "Clawpack"),
                            ("ansys", "Ansys"),
                            ("swbatch", "swbatch"),
                            ("extract", "Extract"),
                        ],
                        help_text="The icon associated with this app.",
                        max_length=64,
                    ),
                ),
                (
                    "popular",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as popular on tools & apps overview.",
                    ),
                ),
                (
                    "license_type",
                    models.CharField(
                        choices=[("OS", "Open Source"), ("LS", "Licensed")],
                        default="OS",
                        help_text="License Type",
                        max_length=2,
                    ),
                ),
                (
                    "available",
                    models.BooleanField(
                        default=True, help_text="App visibility in app tray"
                    ),
                ),
                (
                    "app_id",
                    models.CharField(
                        help_text="The id of this app or app bundle. The id appears in the unique url path to the app.",
                        max_length=64,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="The category for this app entry.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workspace.apptraycategory",
                    ),
                ),
                (
                    "overview",
                    models.CharField(
                        blank=True,
                        help_text="Link to overview page for this app.",
                        max_length=128,
                    ),
                ),
                (
                    "related_apps",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Related apps that will display on app overview page",
                        related_name="+",
                        to="workspace.appitem",
                    ),
                ),
                (
                    "bundled_apps",
                    models.ManyToManyField(
                        help_text="Apps that will be bundled together",
                        related_name="app_bundle",
                        to="workspace.appitem",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="appbundle",
            constraint=models.UniqueConstraint(
                fields=("category", "app_id"), name="unique_category_and_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="appitem",
            constraint=models.UniqueConstraint(
                fields=("category", "app_id", "version"),
                name="unique_category_and_id_and_version",
            ),
        ),
        migrations.AlterField(
            model_name="appbundle",
            name="bundled_apps",
            field=models.ManyToManyField(
                help_text="Apps that will be bundled together.",
                related_name="app_bundle",
                to="workspace.appitem",
            ),
        ),
        migrations.AlterField(
            model_name="appbundle",
            name="license_type",
            field=models.CharField(
                choices=[("OS", "Open Source"), ("LS", "Licensed")],
                default="OS",
                help_text="License Type.",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="appbundle",
            name="related_apps",
            field=models.ManyToManyField(
                blank=True,
                help_text="Related apps that will display on app overview page.",
                related_name="+",
                to="workspace.appitem",
            ),
        ),
        migrations.AlterField(
            model_name="appitem",
            name="app_type",
            field=models.CharField(
                choices=[("tapis", "Tapis"), ("html", "HTML")],
                default="tapis",
                help_text="Application type.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="appitem",
            name="html",
            field=models.TextField(
                blank=True,
                default="",
                help_text="HTML definition to display when app is loaded.",
            ),
        ),
        migrations.AlterField(
            model_name="appitem",
            name="license_type",
            field=models.CharField(
                choices=[("OS", "Open Source"), ("LS", "Licensed")],
                default="OS",
                help_text="License Type.",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="appitem",
            name="version",
            field=models.CharField(
                blank=True,
                help_text="The version number of the app. The app id + version denotes a unique app.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="apptraycategory",
            name="category",
            field=models.CharField(
                help_text="A category for the app tray.", max_length=64, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="apptraycategory",
            name="priority",
            field=models.IntegerField(
                default=0,
                help_text="Category priority, where higher number tabs appear before lower ones.",
            ),
        ),
        migrations.CreateModel(
            name="AppTrayEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app_type",
                    models.CharField(
                        choices=[
                            ("tapis", "Tapis App"),
                            ("html", "HTML or External app"),
                            ("bundle", "App Bundle"),
                        ],
                        default="tapis",
                        help_text="Application type.",
                        max_length=10,
                    ),
                ),
                (
                    "app_id",
                    models.CharField(
                        help_text="The id of this app or app bundle. The id appears in the unique url path to the app.",
                        max_length=64,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="The display name of this app in the Apps Tray.",
                        max_length=64,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rwhale", "rWHALE"),
                            ("hazmapper", "Hazmapper"),
                            ("compress", "Compress"),
                            ("opensees", "OpenSees/STKO"),
                            ("openfoam", "OpenFOAM"),
                            ("blender", "Blender"),
                            ("matlab", "MATLAB"),
                            ("ngl", "NGL"),
                            ("paraview", "Paraview"),
                            ("visit", "VisIt"),
                            ("jupyter", "Jupyter"),
                            ("qgis", "QGIS"),
                            ("adcirc", "ADCIRC"),
                            ("opensees", "OpenSees"),
                            ("ls-dyna", "LS-DYNA"),
                            ("dakota", "Dakota"),
                            ("clawpack", "Clawpack"),
                            ("ansys", "Ansys"),
                            ("swbatch", "swbatch"),
                            ("extract", "Extract"),
                        ],
                        help_text="The icon associated with this app.",
                        max_length=64,
                    ),
                ),
                (
                    "available",
                    models.BooleanField(
                        default=True, help_text="App visibility in app tray"
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="The version number of the app. The app id + version denotes a unique app.",
                        max_length=64,
                    ),
                ),
                (
                    "html",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="HTML definition to display when app is loaded.",
                    ),
                ),
                (
                    "popular",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as popular on tools & apps overview.",
                    ),
                ),
                (
                    "license_type",
                    models.CharField(
                        choices=[("OS", "Open Source"), ("LS", "Licensed")],
                        default="OS",
                        help_text="License Type.",
                        max_length=2,
                    ),
                ),
                (
                    "overview",
                    models.CharField(
                        blank=True,
                        help_text="Link to overview page for this app.",
                        max_length=128,
                    ),
                ),
                (
                    "bundled_apps",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Apps that will be bundled together.",
                        to="workspace.apptrayentry",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="The category for this app entry.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workspace.apptraycategory",
                    ),
                ),
                (
                    "related_apps",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Related apps that will display on app overview page.",
                        to="workspace.apptrayentry",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="appitem",
            name="category",
        ),
        migrations.RemoveField(
            model_name="appitem",
            name="related_apps",
        ),
        migrations.DeleteModel(
            name="AppBundle",
        ),
        migrations.DeleteModel(
            name="AppItem",
        ),
        migrations.AddConstraint(
            model_name="apptrayentry",
            constraint=models.UniqueConstraint(
                fields=("category", "app_id", "version"),
                name="unique_category_and_id_and_version",
            ),
        ),
    ]
