# Generated by Django 4.2.6 on 2024-03-01 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0002_auto_20200423_1940"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppTrayCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="A category for the app tray.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Category priority, where higher number tabs appear before lower ones.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "App Categories",
            },
        ),
        migrations.CreateModel(
            name="AppListingEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="The display name of this bundle in the Apps Tray.",
                        max_length=64,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rwhale", "rWHALE"),
                            ("hazmapper", "Hazmapper"),
                            ("compress", "Compress"),
                            ("opensees", "OpenSees/STKO"),
                            ("openfoam", "OpenFOAM"),
                            ("blender", "Blender"),
                            ("matlab", "MATLAB"),
                            ("ngl", "NGL"),
                            ("paraview", "Paraview"),
                            ("visit", "VisIt"),
                            ("jupyter", "Jupyter"),
                            ("qgis", "QGIS"),
                            ("adcirc", "ADCIRC"),
                            ("opensees", "OpenSees"),
                            ("ls-dyna", "LS-DYNA"),
                            ("dakota", "Dakota"),
                            ("clawpack", "Clawpack"),
                            ("ansys", "Ansys"),
                            ("swbatch", "swbatch"),
                            ("extract", "Extract"),
                        ],
                        help_text="The icon associated with this app.",
                        max_length=64,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="App listing entry visibility in app tray",
                    ),
                ),
                (
                    "popular",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as popular on tools & apps overview.",
                    ),
                ),
                (
                    "not_bundled",
                    models.BooleanField(
                        default=False,
                        help_text="Select if this entry represents a single app ID and not a bundle",
                    ),
                ),
                (
                    "href",
                    models.CharField(
                        blank=True,
                        help_text="Link to overview page for this app.",
                        max_length=128,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="The category for this app entry.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workspace.apptraycategory",
                    ),
                ),
                (
                    "related_apps",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Related apps that will display on app overview page.",
                        to="workspace.applistingentry",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "App Listing Entries",
            },
        ),
        migrations.CreateModel(
            name="AppVariant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app_id",
                    models.CharField(
                        help_text="The id of this app or app bundle. The id appears in the unique url path to the app.",
                        max_length=64,
                    ),
                ),
                (
                    "app_type",
                    models.CharField(
                        choices=[
                            ("tapis", "Tapis App"),
                            ("html", "HTML or External app"),
                        ],
                        default="tapis",
                        help_text="Application type.",
                        max_length=10,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="The display name of this app in the Apps Tray.",
                        max_length=64,
                    ),
                ),
                (
                    "license_type",
                    models.CharField(
                        choices=[("OS", "Open Source"), ("LS", "Licensed")],
                        default="OS",
                        help_text="License Type.",
                        max_length=2,
                    ),
                ),
                (
                    "html",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="HTML definition to display when app is loaded.",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The version number of the app. The app id + version denotes a unique app.",
                        max_length=64,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True, help_text="App variant visibility in app tray"
                    ),
                ),
                (
                    "bundle",
                    models.ForeignKey(
                        blank=True,
                        help_text="bundle that the app belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workspace.applistingentry",
                    ),
                ),
            ],
        ),
    ]
