# Generated by Django 4.2.6 on 2024-03-20 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0002_auto_20200423_1940"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppTrayCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="A category for the app tray.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Category priority, where higher number tabs appear before lower ones.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "App Categories",
            },
        ),
        migrations.CreateModel(
            name="AppTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A tag associated with an app.",
                        max_length=64,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AppListingEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="The display name of this bundle in the Apps Tray. Not used if this entry is a single app ID.",
                        max_length=64,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("adcirc", "ADCIRC"),
                            ("ansys", "Ansys"),
                            ("blender", "Blender"),
                            ("clawpack", "Clawpack"),
                            ("compress", "Compress"),
                            ("dakota", "Dakota"),
                            ("extract", "Extract"),
                            ("hazmapper", "Hazmapper"),
                            ("jupyter", "Jupyter"),
                            ("ls-dyna", "LS-DYNA"),
                            ("matlab", "MATLAB"),
                            ("ngl", "NGL"),
                            ("openfoam", "OpenFOAM"),
                            ("opensees", "OpenSees"),
                            ("paraview", "Paraview"),
                            ("qgis", "QGIS"),
                            ("rwhale", "rWHALE"),
                            ("stko", "STKO"),
                            ("swbatch", "swbatch"),
                            ("visit", "VisIt"),
                        ],
                        help_text="The icon associated with this app.",
                        max_length=64,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True, help_text="App bundle visibility in app tray."
                    ),
                ),
                (
                    "is_popular",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as popular on tools & apps overview.",
                    ),
                ),
                (
                    "href",
                    models.CharField(
                        blank=True,
                        help_text="Link to overview page for this app.",
                        max_length=128,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="The category for this app entry.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workspace.apptraycategory",
                    ),
                ),
                (
                    "related_apps",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Related apps that will display on app overview page.",
                        to="workspace.applistingentry",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="App bundle description text for tools & apps overview.",
                    ),
                ),
                (
                    "is_simcenter",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as 'True' if the app is built by the SimCenter team.",
                    ),
                ),
                (
                    "license_type",
                    models.CharField(
                        choices=[("OS", "Open Source"), ("LS", "Licensed")],
                        default="OS",
                        help_text="License Type.",
                        max_length=2,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "App Listing Entries",
            },
        ),
        migrations.CreateModel(
            name="AppVariant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app_id",
                    models.CharField(
                        help_text="The id of this app or app bundle. The id appears in the unique url path to the app.",
                        max_length=64,
                    ),
                ),
                (
                    "app_type",
                    models.CharField(
                        choices=[
                            ("tapis", "Tapis App"),
                            ("html", "HTML or External app"),
                        ],
                        default="tapis",
                        help_text="Application type.",
                        max_length=10,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="The display name of this app in the Apps Tray. If not defined, uses notes.label from app definition.",
                        max_length=64,
                    ),
                ),
                (
                    "html",
                    models.TextField(
                        blank=True,
                        help_text="HTML definition to display when app is loaded.",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The version number of the app. The app id + version denotes a unique app.",
                        max_length=64,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True, help_text="App variant visibility in app tray."
                    ),
                ),
                (
                    "bundle",
                    models.ForeignKey(
                        blank=True,
                        help_text="Bundle that the app belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workspace.applistingentry",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="applistingentry",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("is_popular", True), ("is_simcenter", True), _negated=True
                ),
                name="not_both_popular_and_simcenter",
            ),
        ),
        migrations.AddConstraint(
            model_name="appvariant",
            constraint=models.UniqueConstraint(
                fields=("app_id", "version", "bundle"), name="unique_apps_per_bundle"
            ),
        ),
        migrations.AddField(
            model_name="applistingentry",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="App bundle tags for tools & apps overview.",
                to="workspace.apptag",
            ),
        ),
    ]
