# Generated by Django 4.2.6 on 2024-01-25 23:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0002_auto_20200423_1940"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appdescription",
            old_name="appDescription",
            new_name="appdescription",
        ),
        migrations.RenameField(
            model_name="appdescription",
            old_name="appId",
            new_name="appid",
        ),
    ]
