# Generated by Django 4.2.6 on 2024-03-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0004_initial_app_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A tag associated with an app.",
                        max_length=64,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="applistingentry",
            old_name="popular",
            new_name="is_popular",
        ),
        migrations.RemoveField(
            model_name="applistingentry",
            name="not_bundled",
        ),
        migrations.RemoveField(
            model_name="appvariant",
            name="license_type",
        ),
        migrations.AddField(
            model_name="applistingentry",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="App bundle description text for tools & apps overview.",
            ),
        ),
        migrations.AddField(
            model_name="applistingentry",
            name="is_simcenter",
            field=models.BooleanField(
                default=False,
                help_text="Mark as 'True' if the app is built by the SimCenter team.",
            ),
        ),
        migrations.AddField(
            model_name="applistingentry",
            name="license_type",
            field=models.CharField(
                choices=[("OS", "Open Source"), ("LS", "Licensed")],
                default="OS",
                help_text="License Type.",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="applistingentry",
            name="label",
            field=models.CharField(
                blank=True,
                help_text="The display name of this bundle in the Apps Tray. Not used if this entry is a single app ID.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="appvariant",
            name="html",
            field=models.TextField(
                blank=True, help_text="HTML definition to display when app is loaded."
            ),
        ),
        migrations.AddConstraint(
            model_name="applistingentry",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("is_popular", True), ("is_simcenter", True), _negated=True
                ),
                name="not_both_popular_and_simcenter",
            ),
        ),
        migrations.AddConstraint(
            model_name="appvariant",
            constraint=models.UniqueConstraint(
                fields=("app_id", "version", "bundle"),
                name="unique_apps_per_bundle",
            ),
        ),
        migrations.AddField(
            model_name="applistingentry",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="App bundle tags for tools & apps overview.",
                to="workspace.apptag",
            ),
        ),
    ]
