# Generated by Django 4.2.6 on 2024-04-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0005_appcategorylistingplugin"),
    ]

    operations = [
        migrations.AddField(
            model_name="appvariant",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="App variant description text for version overview.",
                null=True,
            ),
        ),
    ]
