# Generated by Django 4.2.11 on 2024-04-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0008_appvariantsplugin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applistingentry",
            name="icon",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Generic-App", "Generic: Application"),
                    ("Generic-Vis", "Generic: Visualization"),
                    ("Earth", "Element: Earth"),
                    ("Water", "Element: Water"),
                    ("Wind", "Element: Wind"),
                    ("All-Hazards", "All Hazards"),
                    ("adcirc", "ADCIRC"),
                    ("Ansys", "Ansys"),
                    ("Blender", "Blender"),
                    ("Clawpack", "Clawpack"),
                    ("Compress", "Compress"),
                    ("Dakota", "Dakota"),
                    ("Extract", "Extract"),
                    ("GiD", "GiD"),
                    ("Hazmapper", "Hazmapper"),
                    ("HVSR", "HVSR"),
                    ("Jupyter", "Jupyter"),
                    ("LS-DYNA", "LS-DYNA"),
                    ("MATLAB", "MATLAB"),
                    ("MPM", "MPM"),
                    ("NGL-without-text", "NGL"),
                    ("OpenFOAM", "OpenFOAM"),
                    ("OpenSees", "OpenSees"),
                    ("Paraview", "Paraview"),
                    ("Potree", "Potree"),
                    ("QGIS", "QGIS"),
                    ("rWHALE", "rWHALE"),
                    ("STKO", "STKO"),
                    ("SWBatch", "SWBatch"),
                ],
                help_text="The icon associated with this app.",
                max_length=64,
            ),
        ),
    ]
