# Generated by Django 4.2.11 on 2024-04-26 15:49

from django.db import migrations, models
import django.db.models.functions.comparison


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0009_alter_applistingentry_icon"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applistingentry",
            options={
                "ordering": ["label", "is_popular"],
                "verbose_name_plural": "App Listing Entries",
            },
        ),
        migrations.AlterModelOptions(
            name="appvariant",
            options={
                "ordering": [
                    django.db.models.functions.comparison.Coalesce("label", "app_id"),
                    "priority",
                ]
            },
        ),
        migrations.AddField(
            model_name="appvariant",
            name="priority",
            field=models.IntegerField(
                default=0,
                help_text="App variant priority, rendered in ascending order.",
            ),
        ),
    ]
