# Generated by Django 4.2.11 on 2024-04-29 16:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0010_alter_applistingentry_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applistingentry",
            options={
                "ordering": ["-is_popular", "label"],
                "verbose_name_plural": "App Listing Entries",
            },
        ),
    ]
