# Generated by Django 4.2.6 on 2024-05-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0012_alter_applistingentry_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appvariant",
            name="label",
            field=models.CharField(
                blank=True,
                help_text="The display name of this app in the Apps Tray (not the CMS app listing). If not defined, uses notes.label from app definition.",
                max_length=64,
            ),
        ),
    ]
