# Generated by Django 4.2.11 on 2024-05-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0012_alter_applistingentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appvariant',
            name='shortLabel',
            field=models.CharField(blank=True, help_text='The display name of this app in the Apps Tray. If not defined, uses notes.shortLabel from app definition.', max_length=64),
        ),
        migrations.AlterField(
            model_name='appvariant',
            name='label',
            field=models.CharField(blank=True, help_text='The display name of this app on the Apps submission form. If not defined, uses notes.label from app definition.', max_length=64),
        ),
    ]
