# Generated by Django 4.2.11 on 2024-08-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0017_alter_applistingentry_options_ordering"),
    ]

    operations = [
        migrations.AddField(
            model_name="appvariant",
            name="external_href",
            field=models.CharField(
                blank=True,
                help_text="Path or URL to external access for this variant.",
                max_length=128,
                verbose_name="external HREF",
            ),
        ),
    ]
