# Generated by Django 4.2.11 on 2024-08-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0017_alter_applistingentry_options_ordering"),
    ]

    operations = [
        migrations.AddField(
            model_name="appvariant",
            name="download_href",
            field=models.CharField(
                blank=True,
                help_text="Link to download location for this variant.",
                max_length=128,
            ),
        ),
    ]
