# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-05 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_auto_20190304_1958"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoryorder",
            name="parent",
            field=models.CharField(
                blank=True, editable=False, max_length=255, null=True
            ),
        ),
    ]
