# This compose file is useful for debugging with ipdb


version: "2"
services:
  redis:
    image: redis

  rabbitmq:
    image: rabbitmq

  elasticsearch:
    image: elasticsearch:5.5.1
    volumes:
      - ./data/elasticsearch:/data
    ports:
      - 9200:9200

  mysql:
    image: mysql:5.6
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: DS_DEV
      MYSQL_DATABASE: DS_DEV
      MYSQL_USER: DS_DEV
      MYSQL_PASSWORD: DS_DEV

  memcached:
    image: memcached

  uwsgi:
    build: .
    env_file: ../../designsafe.env
    volumes:
      - .:/portal
    environment:
      - DJANGO_SETTINGS_MODULE=designsafe.http_debug_settings
      - DATABASE_HOST=mysql
      - DATABASE_NAME=DS_DEV
      - DATABASE_PORT=3306
      - DATABASE_USER=DS_DEV
      - DATABASE_PASSWORD=DS_DEV
      - DS_LOCAL_DEV=True
      - WS_BACKEND_HOST=redis
      - WS_BACKEND_DB=0
      - WS_BACKEND_PORT=6379
      - CELERY_BROKER_URL_HOST=rabbitmq
      - CELERY_BROKER_URL_PORT=5672
      - CELERY_BROKER_URL_VHOST=
      - CELERY_BROKER_URL_USERNAME=guest
      - CELERY_BROKER_URL_PWD=guest
      - CELERY_BROKER_URL_PROTOCOL=amqp://
      - CELERY_RESULT_BACKEND_HOST=redis
      - CELERY_RESULT_BACKEND_PORT=6379
    links:
      - redis
    ports:
      - 9000:9000
    command: ./bin/run-uwsgi.sh


  django:
    stdin_open: true
    tty: true
    build: .
    env_file: ../../designsafe.env
    environment:
      - DJANGO_SETTINGS_MODULE=designsafe.http_debug_settings
      - DATABASE_HOST=mysql
      - DATABASE_NAME=DS_DEV
      - DATABASE_PORT=3306
      - DATABASE_USER=DS_DEV
      - DATABASE_PASSWORD=DS_DEV
      - DS_LOCAL_DEV=True
      - WS_BACKEND_HOST=redis
      - WS_BACKEND_DB=0
      - WS_BACKEND_PORT=6379
      - CELERY_BROKER_URL_HOST=rabbitmq
      - CELERY_BROKER_URL_PORT=5672
      - CELERY_BROKER_URL_VHOST=
      - CELERY_BROKER_URL_USERNAME=guest
      - CELERY_BROKER_URL_PWD=guest
      - CELERY_BROKER_URL_PROTOCOL=amqp://
      - CELERY_RESULT_BACKEND_HOST=redis
      - CELERY_RESULT_BACKEND_PORT=6379
    links:
      - redis:redis
      - memcached:memcached
      - elasticsearch:elasticsearch
      - mysql:mysql
      - worker:worker
      - rabbitmq:rabbitmq
    volumes:
      - ../../.:/srv/www/designsafe
      - /corral-repl/tacc/NHERI:/corral-repl/tacc/NHERI
      - /var/www/designsafe-ci.org/static
      - /var/www/designsafe-ci.org/media
    ports:
      - 8000:8000
      - 5555:5555
    dns:
      - 8.8.8.8
      - 8.8.4.4
    #command: /usr/local/bin/uwsgi --ini /portal/conf/uwsgi.ini
    command: ./bin/run-django.sh

  nginx:
    image: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/gzip.conf:/etc/nginx/gzip.conf
      - ./conf/dummy.crt:/etc/ssl/dummy.crt
      - ./conf/dummy.key:/etc/ssl/dummy.key
      - ./conf/dhparam.pem:/etc/ssl/dhparam.pem
    volumes_from:
      - django
    links:
      - django:django
    ports:
      - 80:80
      - 443:443

  # devnginx:
  #   image: nginx
  #   volumes:
  #     - ./conf/nginx.conf:/etc/nginx/nginx.conf
  #     - ./conf/gzip.conf:/etc/nginx/gzip.conf
  #     - ./conf/dummy.crt:/etc/ssl/dummy.crt
  #     - ./conf/dummy.key:/etc/ssl/dummy.key
  #     - ./conf/dhparam.pem:/etc/ssl/dhparam.pem
  #   volumes_from:
  #     - django
  #   ports:
  #     - 80:80
  #     - 443:443
  #   external_links:
  #     - portal_django_run_1:django


  worker:
    build: .
    env_file: ../../designsafe.env
    environment:
      - DJANGO_SETTINGS_MODULE=designsafe.http_debug_settings
      - DATABASE_HOST=mysql
      - DATABASE_NAME=DS_DEV
      - DATABASE_PORT=3306
      - DATABASE_USER=DS_DEV
      - DATABASE_PASSWORD=DS_DEV
      - DS_LOCAL_DEV=True
      - WS_BACKEND_HOST=redis
      - WS_BACKEND_DB=0
      - WS_BACKEND_PORT=6379
      - BROKER_URL_PROTOCOL=amqp://
      - CELERY_BROKER_URL_HOST=rabbitmq
      - CELERY_BROKER_URL_PORT=5672
      - CELERY_BROKER_URL_VHOST=
      - CELERY_BROKER_URL_USERNAME=guest
      - CELERY_BROKER_URL_PWD=guest
      - CELERY_BROKER_URL_PROTOCOL=amqp://
      - CELERY_RESULT_BACKEND_HOST=redis
      - CELERY_RESULT_BACKEND_PORT=6379
    links:
      - redis:redis
      - memcached:memcached
      - elasticsearch:elasticsearch
      - mysql:mysql
      - rabbitmq:rabbitmq
    volumes:
      - ../../.:/srv/www/designsafe
      - /corral-repl/tacc/NHERI:/corral-repl/tacc/NHERI
    dns:
      - 8.8.8.8
      - 8.8.4.4
    command: ./bin/run-celery.sh
    depends_on:
      - rabbitmq
      - redis
      - memcached
