# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-21 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataFilesSurveyCounter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="DataFilesSurveyResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_id", models.CharField(max_length=255)),
                ("comments", models.CharField(blank=True, default="", max_length=4096)),
                ("reasons", models.CharField(max_length=4096)),
                ("professional_level", models.CharField(max_length=255)),
                ("did_collect", models.BooleanField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
