# Generated by Django 4.2.15 on 2025-06-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datafiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationSymlink",
            fields=[
                (
                    "tapis_accessor",
                    models.CharField(max_length=512, primary_key=True, serialize=False),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("file", "File"), ("dir", "Directory")], max_length=255
                    ),
                ),
            ],
        ),
    ]
