# Generated by Django 4.2.15 on 2025-06-19 15:38

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datafiles', '0002_userfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavorite',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 19, 15, 35, 58, 410115)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfavorite',
            name='tool_id',
            field=models.CharField(default='unknown-tool', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userfavorite',
            unique_together={('user', 'tool_id')},
        ),
        migrations.RemoveField(
            model_name='userfavorite',
            name='file_path',
        ),
    ]
