PUBLISHED_SIM_FIXTURE = {
    "graph": {},
    "links": [
        {"source": "NODE_ROOT", "target": "NODE_9cf0229a-0b8d-47e7-99fd-b08119c1d520"},
        {
            "source": "NODE_9cf0229a-0b8d-47e7-99fd-b08119c1d520",
            "target": "NODE_5469bcb4-60a7-4c2b-a855-58fdea0a281c",
        },
        {
            "source": "NODE_5469bcb4-60a7-4c2b-a855-58fdea0a281c",
            "target": "NODE_5a2eeb8e-9612-499c-bc43-e84d654bc436",
        },
        {
            "source": "NODE_5a2eeb8e-9612-499c-bc43-e84d654bc436",
            "target": "NODE_401565e2-2271-4b2c-b822-f89935a5a15f",
        },
    ],
    "nodes": [
        {
            "id": "NODE_ROOT",
            "name": "designsafe.project",
            "uuid": "6705376950204689940-242ac118-0001-012",
            "value": {
                "ef": "",
                "pi": "xidazhi",
                "dois": [],
                "coPis": [],
                "title": "Physical Drivers for the Increasing Landfalling TC Rainfall Hazard",
                "users": [
                    {
                        "inst": "Princeton University (princeton.edu)",
                        "role": "pi",
                        "email": "dxi@princeton.edu",
                        "fname": "Dazhi",
                        "lname": "Xi",
                        "username": "xidazhi",
                    },
                    {
                        "inst": "Princeton University (princeton.edu)",
                        "role": "team_member",
                        "email": "nlin@princeton.edu",
                        "fname": "Ning",
                        "lname": "Lin",
                        "username": "nlin",
                    },
                ],
                "authors": [],
                "frTypes": [],
                "license": "Open Data Commons Attribution",
                "nhEvent": "",
                "nhTypes": [
                    {
                        "id": "hurricane/tropical storm",
                        "name": "Hurricane/Tropical Storm",
                    }
                ],
                "fileObjs": [],
                "fileTags": [],
                "keywords": ["tropical cyclone", "rainfall", "climate change"],
                "nhEvents": [],
                "dataTypes": [],
                "projectId": "PRJ-3462",
                "tombstone": False,
                "facilities": [],
                "nhLatitude": "",
                "nhLocation": "",
                "description": "This project examines how US landfalling tropical cyclone rainfall will change in the future. The data contains the individual influence of each physical drivers that cause the increase of landfalling tropical cyclone rainfall hazards.",
                "nhLongitude": "",
                "projectType": "simulation",
                "teamMembers": ["nlin"],
                "awardNumbers": [{"name": "NSF", "order": 0, "number": "1854993"}],
                "guestMembers": [],
                "hazmapperMaps": [],
                "referencedData": [],
                "associatedProjects": [],
            },
            "basePath": "/PRJ-3462",
            "projectType": "simulation",
        },
        {
            "id": "NODE_9cf0229a-0b8d-47e7-99fd-b08119c1d520",
            "name": "designsafe.project.simulation",
            "uuid": "2462369419017785836-242ac118-0001-012",
            "order": 0,
            "value": {
                "dois": ["10.17603/ds2-gjms-nj68"],
                "title": "parameter influence on tropical cyclone rainfall",
                "authors": [
                    {
                        "inst": "Princeton University",
                        "name": "xidazhi",
                        "role": "team_member",
                        "email": "dxi@princeton.edu",
                        "fname": "Dazhi",
                        "guest": False,
                        "lname": "Xi",
                        "order": 0,
                        "username": "xidazhi",
                        "authorship": True,
                    },
                    {
                        "inst": "Princeton University",
                        "name": "nlin",
                        "role": "team_member",
                        "email": "nlin@princeton.edu",
                        "fname": "Ning",
                        "guest": False,
                        "lname": "Lin",
                        "order": 1,
                        "username": "nlin",
                        "authorship": True,
                    },
                ],
                "project": ["6705376950204689940-242ac118-0001-012"],
                "tombstone": False,
                "description": "influence of each individual parameter on tropical cyclone rainfall and the equivalent frequency",
                "relatedWork": [],
                "referencedData": [],
                "simulationType": {"id": "other", "name": "tropical cyclone rainfall"},
            },
            "status": "published",
            "version": 1,
            "basePath": "/PRJ-3462",
            "publicationDate": "2022-04-17T14:12:36.030731",
        },
        {
            "id": "NODE_5469bcb4-60a7-4c2b-a855-58fdea0a281c",
            "name": "designsafe.project.simulation.model",
            "uuid": "39160484206219756-242ac118-0001-012",
            "order": 0,
            "value": {
                "files": ["2217017659886997996-242ac112-0001-002"],
                "title": "TCR model",
                "nhType": "",
                "project": ["6705376950204689940-242ac118-0001-012"],
                "fileObjs": [
                    {
                        "name": "README.docx",
                        "path": "/PRJ-3462/README.docx",
                        "type": "file",
                        "system": "designsafe.storage.published",
                    }
                ],
                "fileTags": [],
                "description": "",
                "nhTypeOther": "",
                "simulations": ["2462369419017785836-242ac118-0001-012"],
                "simulatedSystem": "",
                "applicationVersion": "",
                "applicationVersionDesc": "",
                "applicationVersionOther": "",
            },
            "basePath": "/PRJ-3462",
        },
        {
            "id": "NODE_5a2eeb8e-9612-499c-bc43-e84d654bc436",
            "name": "designsafe.project.simulation.input",
            "uuid": "1123553827100299756-242ac118-0001-012",
            "order": 0,
            "value": {
                "files": ["2217017659886997996-242ac112-0001-002"],
                "title": "Simulation input",
                "project": ["6705376950204689940-242ac118-0001-012"],
                "fileObjs": [
                    {
                        "name": "README.docx",
                        "path": "/PRJ-3462/README.docx",
                        "type": "file",
                        "system": "designsafe.storage.published",
                    }
                ],
                "fileTags": [],
                "description": "",
                "simulations": ["2462369419017785836-242ac118-0001-012"],
                "modelConfigs": ["39160484206219756-242ac118-0001-012"],
            },
            "basePath": "/PRJ-3462",
        },
        {
            "id": "NODE_401565e2-2271-4b2c-b822-f89935a5a15f",
            "name": "designsafe.project.simulation.output",
            "uuid": "2983047816888839700-242ac118-0001-012",
            "order": 0,
            "value": {
                "files": [
                    "2217017659886997996-242ac112-0001-002",
                    "483425579106505196-242ac112-0001-002",
                    "1383951372058825196-242ac112-0001-002",
                    "122723155378040340-242ac112-0001-002",
                ],
                "title": "simulation of parameter influence on tropical cyclone rainfall",
                "project": ["6705376950204689940-242ac118-0001-012"],
                "fileObjs": [
                    {
                        "name": "README.docx",
                        "path": "/PRJ-3462/README.docx",
                        "type": "file",
                        "system": "designsafe.storage.published",
                    },
                    {
                        "name": "spatial_eq_update.mat",
                        "path": "/PRJ-3462/spatial_eq_update.mat",
                        "type": "file",
                        "system": "designsafe.storage.published",
                    },
                    {
                        "name": "spatial_frequency.mat",
                        "path": "/PRJ-3462/spatial_frequency.mat",
                        "type": "file",
                        "system": "designsafe.storage.published",
                    },
                    {
                        "name": "spatial_important_update.mat",
                        "path": "/PRJ-3462/spatial_important_update.mat",
                        "type": "file",
                        "system": "designsafe.storage.published",
                    },
                    {
                        "name": "spatial_important_update.mat",
                        "path": "/PRJ-3462/mat-files/spatial_important_update.mat",
                        "type": "file",
                        "system": "designsafe.storage.published",
                    },
                ],
                "fileTags": [
                    {
                        "path": "/PRJ-3462/spatial_eq_update.mat",
                        "tagName": "tropical cyclone",
                    },
                    {"path": "/PRJ-3462/README.docx", "tagName": "tropical cyclone"},
                    {
                        "path": "/PRJ-3462/spatial_frequency.mat",
                        "tagName": "tropical cyclone",
                    },
                    {
                        "path": "/PRJ-3462/spatial_important_update.mat",
                        "tagName": "tropical cyclone",
                    },
                    {
                        "path": "/PRJ-3462/mat-files/spatial_important_update.mat",
                        "tagName": "tropical cyclone (duplicate filename)",
                    },
                ],
                "simInputs": ["1123553827100299756-242ac118-0001-012"],
                "description": "",
                "simulations": ["2462369419017785836-242ac118-0001-012"],
                "modelConfigs": ["39160484206219756-242ac118-0001-012"],
            },
            "basePath": "/PRJ-3462",
        },
    ],
    "directed": True,
    "multigraph": False,
}


PUBLISHED_OTHER_FIXTURE = {
    "graph": {},
    "links": [
        {"source": "NODE_ROOT", "target": "NODE_d1a7e2e6-692f-4c24-b836-ce0c7abfe8b2"},
        {"source": "NODE_ROOT", "target": "NODE_5dc39e3f-033d-437e-8254-c65de12c2d76"},
        {"source": "NODE_ROOT", "target": "NODE_0f8105ce-5900-4747-bfa6-5f1bab78f3ee"},
    ],
    "nodes": [
        {
            "id": "NODE_ROOT",
            "name": None,
            "uuid": None,
            "basePath": "/PRJ-3816v3",
            "projectType": "other",
        },
        {
            "id": "NODE_d1a7e2e6-692f-4c24-b836-ce0c7abfe8b2",
            "name": "designsafe.project",
            "uuid": "1568979524700541421-242ac118-0001-012",
            "value": {
                "ef": "",
                "pi": "castleaw",
                "dois": ["10.17603/ds2-wqy9-rj81"],
                "coPis": [],
                "title": "Should Severe Weather Graphics Wear a Uniform? Implications of inconsistent visual displays on end user uncertainty, risk perception, and behavioral intentions",
                "users": [
                    {
                        "inst": "US National Oceanic and Atmospheric Administration (noaa.gov)",
                        "role": "pi",
                        "email": "castle.williamsberg@noaa.gov",
                        "fname": "Castle",
                        "lname": "Williamsberg",
                        "username": "castleaw",
                    },
                    {
                        "inst": "University of Georgia",
                        "role": "guest",
                        "user": "guestAndrewG0",
                        "email": "andrewg@uga.edu",
                        "fname": "Andrew",
                        "guest": True,
                        "lname": "Grundstein",
                        "order": 1,
                        "username": None,
                    },
                ],
                "authors": [
                    {
                        "inst": "US National Oceanic and Atmospheric Administration (noaa.gov)",
                        "name": "castleaw",
                        "email": "castle.williamsberg@noaa.gov",
                        "fname": "Castle",
                        "guest": False,
                        "lname": "Williamsberg",
                        "order": 0,
                    },
                    {
                        "inst": "University of Georgia",
                        "user": "guestAndrewG0",
                        "email": "andrewg@uga.edu",
                        "fname": "Andrew",
                        "guest": True,
                        "lname": "Grundstein",
                        "order": 1,
                    },
                ],
                "frTypes": [],
                "license": "Open Data Commons Attribution",
                "nhEvent": "",
                "nhTypes": [{"id": "thunderstorm", "name": "Thunderstorm"}],
                "dataType": {"id": "social sciences", "name": "Social Sciences"},
                "fileObjs": [],
                "fileTags": [
                    {
                        "path": "/PRJ-3816/Message Consistency Interview Instrument for Members of the Public_Study 1",
                        "tagName": "Instrument",
                    }
                ],
                "keywords": [
                    "message consistency; severe weather; Convective Outlook; Storm Prediction Center"
                ],
                "nhEvents": [],
                "dataTypes": [{"id": "social sciences", "name": "Social Sciences"}],
                "projectId": "PRJ-3816",
                "tombstone": False,
                "facilities": [],
                "nhLatitude": "",
                "nhLocation": "",
                "description": "With the rise of the Internet and social media platforms, people now have access to more weather information than ever before. Although this allows end users to receive weather information from a variety of sources, the sheer volume of available information likely contributes to a perception that weather risk messages are inconsistent. Members of the weather enterprise share these concerns and believe that these perceived inconsistencies may negatively affect their many audiences. The challenge, however, is that there are only a few studies to-date that have explored message consistency in a weather context. Therefore, in its current state, the weather enterprise lacks empirical evidence that (1) demonstrates that message consistency is a relevant operational concern and (2) provides research-guided recommendations to practitioners and operational meteorologists on how to achieve a more consistent message. To address this operational need, this dissertation conceptualizes ‘message consistency’ for the weather enterprise and employs a social science mixed-methods approach to explore the effects of weather-related graphical inconsistencies on lay public end users. In particular, this project used the Storm Prediction Center’s (SPC) Convective Outlook graphic as a vehicle to investigate the role that visual design plays in keeping a weather-related message consistent.",
                "nhLongitude": "",
                "projectType": "other",
                "teamMembers": [],
                "awardNumbers": [
                    {
                        "name": "NOAA/OAR/WPO Joint Technology Transfer Initiative",
                        "order": 0,
                        "number": "NA18OAR4590366",
                    }
                ],
                "guestMembers": [
                    {
                        "inst": "University of Georgia",
                        "user": "guestAndrewG0",
                        "email": "andrewg@uga.edu",
                        "fname": "Andrew",
                        "guest": True,
                        "lname": "Grundstein",
                        "order": 1,
                    }
                ],
                "hazmapperMaps": [],
                "referencedData": [],
                "associatedProjects": [],
            },
            "status": "published",
            "version": 1,
            "basePath": "/PRJ-3816",
            "projectType": "other",
            "publicationDate": "2023-01-26T18:11:52.343769",
        },
        {
            "id": "NODE_5dc39e3f-033d-437e-8254-c65de12c2d76",
            "name": "designsafe.project",
            "uuid": "1568979524700541421-242ac118-0001-012",
            "value": {
                "ef": "",
                "pi": "castleaw",
                "dois": ["10.17603/ds2-wqy9-rj81"],
                "coPis": [],
                "title": "Should Severe Weather Graphics Wear a Uniform? Implications of inconsistent visual displays on end user uncertainty, risk perception, and behavioral intentions",
                "users": [
                    {
                        "inst": "US National Oceanic and Atmospheric Administration (noaa.gov)",
                        "role": "pi",
                        "email": "castle.williamsberg@noaa.gov",
                        "fname": "Castle",
                        "lname": "Williamsberg",
                        "username": "castleaw",
                    },
                    {
                        "inst": "University of Georgia",
                        "role": "guest",
                        "user": "guestAndrewG0",
                        "email": "andrewg@uga.edu",
                        "fname": "Andrew",
                        "guest": True,
                        "lname": "Grundstein",
                        "order": 1,
                        "username": None,
                    },
                ],
                "authors": [
                    {
                        "inst": "US National Oceanic and Atmospheric Administration (noaa.gov)",
                        "name": "castleaw",
                        "email": "castle.williamsberg@noaa.gov",
                        "fname": "Castle",
                        "guest": False,
                        "lname": "Williamsberg",
                        "order": 0,
                    },
                    {
                        "inst": "University of Georgia",
                        "user": "guestAndrewG0",
                        "email": "andrewg@uga.edu",
                        "fname": "Andrew",
                        "guest": True,
                        "lname": "Grundstein",
                        "order": 1,
                    },
                ],
                "frTypes": [],
                "license": "Open Data Commons Attribution",
                "nhEvent": "",
                "nhTypes": [{"id": "thunderstorm", "name": "Thunderstorm"}],
                "dataType": {"id": "social sciences", "name": "Social Sciences"},
                "fileObjs": [],
                "fileTags": [],
                "keywords": [
                    "message consistency; severe weather; Convective Outlook; Storm Prediction Center"
                ],
                "nhEvents": [],
                "dataTypes": [{"id": "social sciences", "name": "Social Sciences"}],
                "projectId": "PRJ-3816",
                "tombstone": False,
                "facilities": [],
                "nhLatitude": "",
                "nhLocation": "",
                "description": "With the rise of the Internet and social media platforms, people now have access to more weather information than ever before. Although this allows end users to receive weather information from a variety of sources, the sheer volume of available information likely contributes to a perception that weather risk messages are inconsistent. Members of the weather enterprise share these concerns and believe that these perceived inconsistencies may negatively affect their many audiences. The challenge, however, is that there are only a few studies to-date that have explored message consistency in a weather context. Therefore, in its current state, the weather enterprise lacks empirical evidence that (1) demonstrates that message consistency is a relevant operational concern and (2) provides research-guided recommendations to practitioners and operational meteorologists on how to achieve a more consistent message. To address this operational need, this research project conceptualized ‘message consistency’ for the weather enterprise and employs a social science mixed-methods approach to explore the effects of weather-related graphical inconsistencies on lay public end users. In particular, this project used the Storm Prediction Center’s (SPC) Convective Outlook graphic as a vehicle to investigate the role that visual design plays in keeping a weather-related message consistent.",
                "nhLongitude": "",
                "projectType": "other",
                "teamMembers": [],
                "awardNumbers": [
                    {
                        "name": "NOAA/OAR/WPO Joint Technology Transfer Initiative",
                        "order": 0,
                        "number": "NA18OAR4590366",
                    }
                ],
                "guestMembers": [
                    {
                        "inst": "University of Georgia",
                        "user": "guestAndrewG0",
                        "email": "andrewg@uga.edu",
                        "fname": "Andrew",
                        "guest": True,
                        "lname": "Grundstein",
                        "order": 1,
                    }
                ],
                "hazmapperMaps": [],
                "referencedData": [],
                "associatedProjects": [
                    {
                        "doi": "",
                        "href": "https://doi.org/10.25923/8vg7-4f28",
                        "type": "Cited By",
                        "title": "Implications of Inconsistent Visual Displays on End User Risk Perception, Uncertainty, and Behavioral Intentions",
                        "hrefType": "DOI",
                    },
                    {
                        "doi": "",
                        "href": "https://repository.library.noaa.gov/view/noaa/44639",
                        "type": "Cited By",
                        "title": "An examination of the SPC’s Convective Outlook products and risk category system among members of the public",
                        "hrefType": "URL",
                    },
                ],
            },
            "status": "published",
            "version": 2,
            "basePath": "/PRJ-3816v2",
            "projectType": "other",
            "versionDate": "2023-07-07T01:29:46.792",
            "versionInfo": "Adding some additional files that pertain to Study 1 and building out the infrastructure to publish other files and data associated with other studies.",
            "publicationDate": "2023-01-26T18:11:52.343769",
        },
        {
            "id": "NODE_0f8105ce-5900-4747-bfa6-5f1bab78f3ee",
            "name": "designsafe.project",
            "uuid": "1568979524700541421-242ac118-0001-012",
            "value": {
                "ef": "",
                "pi": "castleaw",
                "dois": ["10.17603/ds2-wqy9-rj81"],
                "coPis": [],
                "title": "Should Severe Weather Graphics Wear a Uniform? Implications of inconsistent visual displays on end user uncertainty, risk perception, and behavioral intentions",
                "users": [
                    {
                        "inst": "US National Oceanic and Atmospheric Administration (noaa.gov)",
                        "role": "pi",
                        "email": "castle.williamsberg@noaa.gov",
                        "fname": "Castle",
                        "lname": "Williamsberg",
                        "username": "castleaw",
                    },
                    {
                        "inst": "University of Georgia",
                        "role": "guest",
                        "user": "guestAndrewG0",
                        "email": "andrewg@uga.edu",
                        "fname": "Andrew",
                        "guest": True,
                        "lname": "Grundstein",
                        "order": 1,
                        "username": None,
                    },
                ],
                "authors": [
                    {
                        "inst": "US National Oceanic and Atmospheric Administration (noaa.gov)",
                        "name": "castleaw",
                        "email": "castle.williamsberg@noaa.gov",
                        "fname": "Castle",
                        "guest": False,
                        "lname": "Williamsberg",
                        "order": 0,
                    },
                    {
                        "inst": "University of Georgia",
                        "user": "guestAndrewG0",
                        "email": "andrewg@uga.edu",
                        "fname": "Andrew",
                        "guest": True,
                        "lname": "Grundstein",
                        "order": 1,
                    },
                ],
                "frTypes": [],
                "license": "Open Data Commons Attribution",
                "nhEvent": "",
                "nhTypes": [{"id": "thunderstorm", "name": "Thunderstorm"}],
                "dataType": {"id": "social sciences", "name": "Social Sciences"},
                "fileObjs": [],
                "fileTags": [
                    {
                        "path": "/PRJ-3816v3/Message Consistency - Study 1/Interview Instrument & Vignettes for Members of the Public",
                        "tagName": "Instrument",
                    },
                    {
                        "path": "/PRJ-3816v3/Message Consistency - Study 1/Code Book for Study 1",
                        "tagName": "Codebook",
                    },
                    {
                        "path": "/PRJ-3816v3/Message Consistency - Study 1/Card Sorting Task Data",
                        "tagName": "Data",
                    },
                    {
                        "path": "/PRJ-3816v3/Message Consistency - Study 1/Vignette 1 - Graphics",
                        "tagName": "Image",
                    },
                    {
                        "path": "/PRJ-3816v3/Message Consistency - Study 1/Vignette 2 - Graphics",
                        "tagName": "Image",
                    },
                    {
                        "path": "/PRJ-3816v3/Message Consistency - Study 1/Vignette 3 - Graphics",
                        "tagName": "Image",
                    },
                    {
                        "path": "/PRJ-3816v3/Message Consistency - Study 1/Vignette 4 - Graphics",
                        "tagName": "Image",
                    },
                    {
                        "path": "/PRJ-3816v3/Executive Summary of Five Studies",
                        "tagName": "Report",
                    },
                    {
                        "path": "/PRJ-3816v3/Message Consistency - Study 2/Study 2 - Survey Instrument.docx",
                        "tagName": "Instrument",
                    },
                    {
                        "path": "/PRJ-3816v3/Message Consistency - Study 3/Study 3 - Post-Experiment Survey Instrument.docx",
                        "tagName": "Instrument",
                    },
                    {
                        "path": "/PRJ-3816v3/Message Consistency - Study 3/Study 3 - Pre-Experiment Survey Instrument.docx",
                        "tagName": "Instrument",
                    },
                    {
                        "path": "/PRJ-3816v3/Message Consistency - Study 3/Study 3_Student_Data_Combined.xlsx",
                        "tagName": "Spreadsheet",
                    },
                    {
                        "path": "/PRJ-3816v3/Message Consistency - Study 4/Study4_data_v2.xlsx",
                        "tagName": "Spreadsheet",
                    },
                    {
                        "path": "/PRJ-3816v3/Message Consistency - Study 4/Study 4 Survey Instrument.docx",
                        "tagName": "Instrument",
                    },
                    {
                        "path": "/PRJ-3816v3/Message Consistency - Study 3/Study 3_ExperimentalStimuli.pptx",
                        "tagName": "Image",
                    },
                    {
                        "path": "/PRJ-3816v3/Message Consistency - Study 4/Study 4 - Experimental Stimuli.pptx",
                        "tagName": "Powerpoint",
                    },
                    {
                        "path": "/PRJ-3816v3/Message Consistency - Study 5/Study 5 - Color Question Experimental Stimuli.pptx",
                        "tagName": "Powerpoint",
                    },
                    {
                        "path": "/PRJ-3816v3/Message Consistency - Study 5/Study 5 - Experimental Stimuli.pptx",
                        "tagName": "Powerpoint",
                    },
                    {
                        "path": "/PRJ-3816v3/Message Consistency - Study 5/Study 5 Survey Instrument.docx",
                        "tagName": "Instrument",
                    },
                    {
                        "path": "/PRJ-3816v3/Message Consistency - Study 5/Study5_Data_Categorical Graphics Only.xlsx",
                        "tagName": "Spreadsheet",
                    },
                ],
                "keywords": [
                    "message consistency; severe weather; Convective Outlook; Storm Prediction Center"
                ],
                "nhEvents": [],
                "dataTypes": [{"id": "social sciences", "name": "Social Sciences"}],
                "projectId": "PRJ-3816",
                "tombstone": False,
                "facilities": [],
                "nhLatitude": "",
                "nhLocation": "",
                "description": "With the rise of the Internet and social media platforms, people now have access to more weather information than ever before. Although this allows end users to receive weather information from a variety of sources, the sheer volume of available information likely contributes to a perception that weather risk messages are inconsistent. Members of the weather enterprise share these concerns and believe that these perceived inconsistencies may negatively affect their many audiences. The challenge, however, is that there are only a few studies to-date that have explored message consistency in a weather context. Therefore, in its current state, the weather enterprise lacks empirical evidence that (1) demonstrates that message consistency is a relevant operational concern and (2) provides research-guided recommendations to practitioners and operational meteorologists on how to achieve a more consistent message. To address this operational need, this research project conceptualized ‘message consistency’ for the weather enterprise and employs a social science mixed-methods approach to explore the effects of weather-related graphical inconsistencies on lay public end users. In particular, this project used the Storm Prediction Center’s (SPC) Convective Outlook graphic as a vehicle to investigate the role that visual design plays in keeping a weather-related message consistent.",
                "nhLongitude": "",
                "projectType": "other",
                "teamMembers": [],
                "awardNumbers": [
                    {
                        "name": "NOAA/OAR/WPO Joint Technology Transfer Initiative",
                        "order": 0,
                        "number": "NA18OAR4590366",
                    }
                ],
                "guestMembers": [
                    {
                        "inst": "University of Georgia",
                        "user": "guestAndrewG0",
                        "email": "andrewg@uga.edu",
                        "fname": "Andrew",
                        "guest": True,
                        "lname": "Grundstein",
                        "order": 1,
                    }
                ],
                "hazmapperMaps": [],
                "referencedData": [],
                "associatedProjects": [
                    {
                        "doi": "",
                        "href": "https://doi.org/10.25923/8vg7-4f28",
                        "type": "Cited By",
                        "title": "Implications of Inconsistent Visual Displays on End User Risk Perception, Uncertainty, and Behavioral Intentions",
                        "hrefType": "DOI",
                    },
                    {
                        "doi": "",
                        "href": "https://repository.library.noaa.gov/view/noaa/44639",
                        "type": "Cited By",
                        "title": "An examination of the SPC’s Convective Outlook products and risk category system among members of the public",
                        "hrefType": "URL",
                    },
                ],
            },
            "status": "published",
            "version": 3,
            "basePath": "/PRJ-3816v3",
            "projectType": "other",
            "versionDate": "2024-02-20T23:23:42.555",
            "versionInfo": "Added several new data files, survey instruments, and images of experimental stimuli associated with each unique study.",
            "publicationDate": "2023-01-26T18:11:52.343769",
        },
    ],
    "directed": True,
    "multigraph": False,
}
